TC.EMEA.PropertyEtl.ClientApp/Models/ErrorViewModel.cs
using System;

namespace TC.EMEA.PropertyEtl.ClientApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TC.EMEA.PropertyEtl.ClientApp/Models/S1PropertyModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace TC.EMEA.PropertyEtl.ClientApp.Models
{
    public class S1PropertyModel
    {
        [DisplayName("Id")]
        public int Id { get; set; }

        [DisplayName("Address1")]
        public string Address1 { get; set; }

        [DisplayName("Address2")]
        public string Address2 { get; set; }

        [DisplayName("Latitude")]
        public double? Lat { get; set; }
        
        [DisplayName("Longitude")]
        public double? Lon { get; set; }

        [DisplayName("Floor Count")]
        public int? FloorCount { get; set; }
    }
}

TC.EMEA.PropertyEtl.ClientApp/Models/S2PropertyViewModel.cs
using System.ComponentModel;
using Microsoft.AspNetCore.Http;

namespace TC.EMEA.PropertyEtl.ClientApp.Models
{
    public class S2PropertyViewModel
    {
        [DisplayName("Select file")]
        public IFormFile S2PropertyFile { set; get; }
    }
}

TC.EMEA.PropertyEtl.ClientApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TC.EMEA.PropertyEtl.ClientApp.Models;

namespace TC.EMEA.PropertyEtl.ClientApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string firstName)
        {
            return Content($"Hello {firstName}");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TC.EMEA.PropertyEtl.ClientApp/Controllers/S1PropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TC.EMEA.PropertyEtl.ClientApp.Models;
using TC.EMEA.PropertyEtl.ClientApp.Services;

namespace TC.EMEA.PropertyEtl.ClientApp.Controllers
{
    public class S1PropertyController : Controller
    {
        private readonly HttpGatewayService _gatewayService;

        public S1PropertyController(HttpGatewayService _gatewayService)
        {
            this._gatewayService = _gatewayService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(S1PropertyModel model)
        {
            try
            {
                var response = await this._gatewayService.PostMessage(model);
            }
            catch (Exception exception)
            {
                // log 
                
            }
            return RedirectToAction("Index");
        }
    }
}

TC.EMEA.PropertyEtl.ClientApp/Controllers/S2PropertyController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using TC.EMEA.PropertyEtl.ClientApp.Models;

namespace TC.EMEA.PropertyEtl.ClientApp.Controllers
{
    public class S2PropertyController : Controller
    {
        private string connection = "connection info of storage";
           

        private string containerName = "drop folder name";
        public IActionResult Index()
        {
            return View(new S2PropertyViewModel());
        }

        [HttpPost]
        public async Task <IActionResult> Index(S2PropertyViewModel viewModel)
        {
            if(viewModel == null) return new BadRequestObjectResult("Empty view model");
            if(viewModel.S2PropertyFile == null) return new BadRequestObjectResult("No file to upload");

            try
            {
                var fileName = $"{viewModel.S2PropertyFile.FileName}{Path.GetRandomFileName()}";
                BlobServiceClient client = new BlobServiceClient(connection);
                BlobContainerClient blobContainerClient = client.GetBlobContainerClient(containerName);
                BlobClient blobClient = blobContainerClient.GetBlobClient(fileName);
                using var stream = viewModel.S2PropertyFile.OpenReadStream();
                await blobClient.UploadAsync(stream);
                return RedirectToAction("Index");
            }
            catch (Exception exception)
            {
                // log
                return RedirectToAction("Index");
                
            }
        }
    }
}

TC.EMEA.PropertyEtl.ClientApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    Select the source system link above
</div>

TC.EMEA.PropertyEtl.ClientApp/Views/S1Property/Index.cshtml
@using Microsoft.AspNetCore.Mvc.ModelBinding

@{
    @model S1PropertyModel;
    ViewData["Title"] = "S1 Property";
}

<h5>S1 Property</h5>

<div class="text-left">
    <form asp-action="Index" asp-controller="S1Property">
        <div asp-validation-summary="All"></div>
        <table class="table table-bordered table-striped">
            <tr>
                <td><label asp-for="Id" class="col-sm-2 col-form-label"></label></td>
                <td>
                    <div class="col-md-4">
                        <input asp-for="Id" placeholder="Id" class="form-control"/>
                    </div>
                </td>
            </tr>
            <tr>
                <td><label asp-for="Address1" class="col-sm-2 col-form-label"></label></td>
                <td>
                    <div class="col-md-4">
                        <input asp-for="Address1" placeholder="address1" class="form-control"/>
                    </div>
                </td>
            </tr>
            <tr>
                <td> <label asp-for="Address2" class="col-sm-2 col-form-label"></label></td>
                <td>
                    <div class="col-md-4">
                        <input asp-for="Address2" placeholder="address2" class="form-control"/>
                    </div>
                </td>
            </tr>
            <tr>
                <td> <label asp-for="Lat" class="col-sm-2 col-form-label"></label></td>
                <td>
                    <div class="col-md-4">
                        <input asp-for="Lat" placeholder="Latitude" class="form-control"/>
                    </div>
                </td>
            </tr>
            <tr>
                <td> <label asp-for="Lon" class="col-sm-2 col-form-label"></label></td>
                <td>
                    <div class="col-md-4">
                        <input asp-for="Lon" placeholder="Longitude" class="form-control"/>
                    </div>
                </td>
            </tr>
            <tr>
                <td><label asp-for="FloorCount" class="col-sm-2 col-form-label"></label></td>
                <td>
                    <div class="col-md-4">
                        <input asp-for="FloorCount" placeholder="Floor count" class="form-control"/>
                    </div>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <div class="col-md-4 mt-5">
                        <input type="submit" class="btn btn-success"/>
                    </div>
                </td>
            </tr>
        </table>

    </form>
</div>

TC.EMEA.PropertyEtl.ClientApp/Views/S2Property/Index.cshtml
@{
    @model S2PropertyViewModel
    ViewData["Title"] = "Index";
}

<h5>S2 Property</h5>

<div class="text-left">
    <form asp-action="Index" asp-controller="S2Property" enctype="multipart/form-data">
        <table class="table table-bordered table-striped">
            <tr>
                <td><label asp-for="S2PropertyFile" class="col-sm-2 col-form-label"></label></td>
                <td>
                    <div class="col-md-4">
                        <input asp-for="S2PropertyFile" placeholder="Id" class="form-control" accept="application/json" />
                    </div>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <div class="col-md-4 mt-5">
                        <input type="submit" class="btn btn-success" />
                    </div>
                </td>
            </tr>
        </table>
    </form>
</div>

TC.EMEA.PropertyEtl.ClientApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClientApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TC - ClientApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="S1Property" asp-action="Index">S1Property</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="S2Property" asp-action="Index">S2Property</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TC - ClientApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>